#!/usr/bin/env python3
"""
gen_pr_body.py

Reads changes.yaml (output of sync_stars.py) and writes a Markdown PR body.

Usage:
    python scripts/gen_pr_body.py [--input changes.yaml] [--output pr_body.md]
"""

import argparse
from datetime import datetime
from pathlib import Path

import yaml


def format_sha(sha: str, repo: str, length: int = 7) -> str:
    short = sha[:length]
    url = f"https://github.com/{repo}/commit/{sha}"
    return f"[`{short}`]({url})"


def gen_body(data: dict) -> str:
    changes = data.get("changes", [])
    new_stars = data.get("new_stars", [])
    ts = datetime.fromisoformat(data["checked_at"]).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "## Skills Index Update",
        "",
        f"Auto-generated by `sync_stars.py` on {ts}.",
        "",
    ]

    # ------------------------------------------------------------------
    # Section 1: tracked repos with upstream changes
    # ------------------------------------------------------------------
    if changes:
        lines += [f"### Tracked repos with upstream changes ({len(changes)})", ""]
        for c in changes:
            repo = c["repo"]
            lines.append(f"#### `{repo}`")
            lines.append("")
            if c["reason"] == "new":
                lines.append("- **Status:** First time indexed")
            elif c["reason"] == "updated":
                old = format_sha(c["old_sha"], repo)
                new = format_sha(c["new_sha"], repo)
                compare = f"https://github.com/{repo}/compare/{c['old_sha'][:7]}...{c['new_sha'][:7]}"
                lines.append(f"- **Status:** Updated - {old} -> {new} ([compare]({compare}))")
            lines.append("")

        lines += [
            "**Review checklist:**",
            "- [ ] Does the linked skill need updating?",
            "- [ ] Are there new patterns or anti-patterns to document?",
            "- [ ] Should `watch_paths` in `tracked.yml` be narrowed?",
            "",
        ]

    # ------------------------------------------------------------------
    # Section 2: newly discovered stars
    # ------------------------------------------------------------------
    if new_stars:
        lines += [
            "---",
            "",
            f"### Newly starred repos - not yet linked to a skill ({len(new_stars)})",
            "",
            "These were added to `stubs:` in `tracked.yml`. For each one:",
            "- Promote to `tracked:` and add a `skill:` path, OR",
            "- Leave as a stub for now, OR",
            "- Delete the stub entry if not relevant",
            "",
        ]

        by_lang: dict[str, list] = {}
        for s in new_stars:
            lang = (s.get("state") or {}).get("language") or "Other"
            by_lang.setdefault(lang, []).append(s)

        for lang, items in sorted(by_lang.items()):
            lines.append(f"**{lang}**")
            lines.append("")
            for s in items:
                repo = s["repo"]
                state = s.get("state") or {}
                desc = state.get("description") or ""
                stars = state.get("stargazers_count", "?")
                topics = ", ".join((state.get("topics") or [])[:5])
                url = f"https://github.com/{repo}"
                lines.append(f"- [`{repo}`]({url}) - {desc}")
                if topics:
                    lines.append(f"  - Topics: {topics} | Stars: {stars}")
            lines.append("")

    lines += ["---", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="changes.yaml")
    parser.add_argument("--output", default="pr_body.md")
    args = parser.parse_args()

    data = yaml.safe_load(Path(args.input).read_text())
    body = gen_body(data)
    Path(args.output).write_text(body)
    print(f"PR body written to {args.output}")


if __name__ == "__main__":
    main()
